const {createSupabaseServiceClient,errorResponse,rejectUnknownFields}=require('../_utils');
const {verifySignedRequest}=require('../_trusted-analytics');
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const TYPES=new Set(['form_submitted','booking_created','booking_confirmed','booking_cancelled','appointment_completed','payment_succeeded']);
const META=new Set(['paymentMode','status','test','serviceCategory']);
module.exports=async function(req,res){
  res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return errorResponse(res,405,'METHOD_NOT_ALLOWED','Only POST is allowed');
  const signed=verifySignedRequest(req);if(!signed.valid)return errorResponse(res,signed.code==='STALE_SIGNATURE'?409:401,signed.code,'Signed event verification failed');
  const allowed=['workspaceId','websiteId','sessionId','conversionType','bookingReference','bookingType','occurredAt','revenueMinor','currency','source','sourceEventId','metadata'];if(!rejectUnknownFields(req.body,allowed).valid)return errorResponse(res,400,'INVALID_EVENT','Unknown event fields');
  const b=req.body||{},occurred=new Date(b.occurredAt);if(!UUID.test(b.workspaceId||'')||(b.websiteId&&!UUID.test(b.websiteId))||(b.sessionId&&!UUID.test(b.sessionId))||!TYPES.has(b.conversionType)||!/^[-A-Za-z0-9_:/.]{8,200}$/.test(b.sourceEventId||'')||!Number.isFinite(occurred.getTime())||Math.abs(Date.now()-occurred.getTime())>86400000)return errorResponse(res,400,'INVALID_EVENT','Trusted event payload is invalid');
  if(b.bookingType&&!['shop','mobile'].includes(b.bookingType))return errorResponse(res,400,'INVALID_BOOKING_TYPE','Booking type is invalid');
  const source=b.source||'ks_os';if(!['ks_os','website_server'].includes(source)||b.conversionType!=='form_submitted'&&source!=='ks_os')return errorResponse(res,400,'INVALID_EVENT_SOURCE','Booking and revenue events require KS OS as their signed source');
  const revenue=b.conversionType==='payment_succeeded';if(revenue&&(!Number.isSafeInteger(b.revenueMinor)||b.revenueMinor<0||!/^[A-Z]{3}$/.test(b.currency||'')))return errorResponse(res,400,'INVALID_REVENUE','Verified revenue requires a non-negative minor amount and currency');if(!revenue&&(b.revenueMinor!=null||b.currency!=null))return errorResponse(res,400,'FORGED_REVENUE','Only payment_succeeded may carry revenue');
  const metadata={};if(b.metadata&&typeof b.metadata==='object'&&!Array.isArray(b.metadata))Object.entries(b.metadata).forEach(([k,v])=>{if(META.has(k)&&['string','number','boolean'].includes(typeof v))metadata[k]=typeof v==='string'?v.slice(0,100):v;});
  const db=createSupabaseServiceClient();let websiteId=b.websiteId||null,sessionId=b.sessionId||null;if((!websiteId||!sessionId)&&typeof b.bookingReference==='string'){const {data:link}=await db.from('booking_attribution_links').select('website_id,session_id').eq('workspace_id',b.workspaceId).eq('booking_reference',b.bookingReference).maybeSingle();websiteId=websiteId||link?.website_id||null;sessionId=sessionId||link?.session_id||null;}const {data,error}=await db.rpc('record_trusted_attribution_conversion',{p_workspace_id:b.workspaceId,p_website_id:websiteId,p_session_id:sessionId,p_conversion_type:b.conversionType,p_booking_reference:typeof b.bookingReference==='string'?b.bookingReference.slice(0,200):null,p_booking_type:b.bookingType||null,p_occurred_at:occurred.toISOString(),p_revenue_minor:revenue?b.revenueMinor:null,p_currency:revenue?b.currency:null,p_source:source,p_source_event_id:b.sourceEventId,p_safe_metadata:metadata});
  if(error){await db.from('analytics_runtime_health').upsert({workspace_id:b.workspaceId,component:'trusted_ingestion',status:'failed',last_failure_at:new Date().toISOString(),last_error_code:'CONVERSION_REJECTED',checked_at:new Date().toISOString()},{onConflict:'workspace_id,component'});return errorResponse(res,409,'CONVERSION_REJECTED','Trusted conversion was not accepted');}return res.status(202).json({accepted:true,conversionId:data||null,duplicate:!data});
};
